### ISSUE TITLE
update --language FR

### ISSUE THREAD

**Issue by Zarctus** [LorcanaJSON/LorcanaJSON#4]
Hi there,

When I run "python main.py update --language FR" it says that the "Action 'update' for language 'French' finished after 0.69 seconds at 2024-05-11 15:45:51.190146," but there are no files created in the output folder.

**Comment by Didero** [comment]
The 'update' action only parses new cards. If you ran a 'download' action just before, there will be no difference between the JSON file it downloaded then, and the one 'update' is checking it against now, so it'll think there's nothing to update, and won't parse any cards.
If you run 'python main.py parse --language FR', it should parse all the cards, and it should create output files in 'output/generated/fr'.
Please let me know if that does work!

**Comment by Zarctus** [comment]
It doesn't work, I have these errors:

`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\logging\handlers.py", line 73, in emit
    if self.shouldRollover(record):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\logging\handlers.py", line 194, in shouldRollover
    self.stream = self._open()
                  ^^^^^^^^^^^^
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\logging\__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'P:\\github\\LorcanaJSON\\logs\\LorcanaJSON.log'
Call stack:
  File "P:\github\LorcanaJSON\main.py", line 139, in <module>
    DataFilesGenerator.createOutputFiles(cardIds, shouldShowImages=parsedArguments.shouldShowSubimages)
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 215, in createOutputFiles
    _logger.warning(f"No corrections file found for language '{GlobalConfig.language.code}', assuming no corrections are necessary")
Message: "No corrections file found for language 'fr', assuming no corrections are necessary"
Arguments: ()
2024-05-11 19:04:28 (WARNING) No corrections file found for language 'fr', assuming no corrections are necessary
Exception in thread Thread-1 (worker):
Traceback (most recent call last):
Exception in thread Thread-3 (worker):
Traceback (most recent call last):
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-6 (worker):
Traceback (most recent call last):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-5 (worker):
Traceback (most recent call last):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    self.run()
Exception in thread Thread-4 (worker):
Traceback (most recent call last):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
Exception in thread Thread-7 (worker):
    self.run()
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    self.run()
Exception in thread Thread-8 (worker):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self.run()
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
    self._target(*self._args, **self._kwargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
    initializer(*initargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
    initializer(*initargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self.run()
    initializer(*initargs)
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
    initializer(*initargs)
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
    initializer(*initargs)
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
    self._target(*self._args, **self._kwargs)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
  File "C:\Users\zarct\AppData\Local\Programs\Python\Python311\Lib\multiprocessing\pool.py", line 109, in worker
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
    initializer(*initargs)
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
    initializer(*initargs)
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\github\LorcanaJSON\DataFilesGenerator.py", line 291, in initThread
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    _threadingLocalStorage.imageParser = ImageParser.ImageParser()
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
  File "P:\github\LorcanaJSON\OCR\ImageParser.py", line 35, in __init__
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
    self._tesseractApi = tesserocr.PyTessBaseAPI(lang=modelName, path=GlobalConfig.tesseractPath, psm=tesserocr.PSM.SINGLE_BLOCK)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tesserocr.pyx", line 1219, in tesserocr._tesserocr.PyTessBaseAPI.__cinit__
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
  File "tesserocr.pyx", line 1233, in tesserocr._tesserocr.PyTessBaseAPI._init_api
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON
RuntimeError: Failed to init API, possibly an invalid tessdata path: P:\github\LorcanaJSON`

**Comment by Zarctus** [comment]
Hmmm, i've created the "logs" folder and i've got : (WARNING) No corrections file found for language 'fr', assuming no corrections are necessary

So, I think i must create the outputDataCorrections_fr.json right ?

**Comment by Didero** [comment]
Thanks for posting that tracelog, it's very helpful.

I've just pushed a change that should create the 'logs' folder automatically if it doesn't exist yet, thanks for the report.

That 'corrections' warning can safely be ignored, it just means that no corrections exist for the current language, which means the endresults may not be perfect. I'm currently working on a corrections file for French, which will hopefully be finished in a few weeks, time permitting, which should give much better results than currently.

The last lines in your traceback say "Failed to init API, possibly an invalid tessdata path". This means that the Tesseract model for the language you're using is missing.
I've now added an extra line to the 'Tesseract models' section of the readme describing where to get the Tesseract models for non-English languages.
Sorry for this oversight and the resulting confusion. Initially LorcanaJSON was focussed on English, I'm currently working on expanding the language support throughout the project, so there might be some hiccups in the process. But reports like this really help in fixing these, so thanks!

**Comment by Zarctus** [comment]
Thank you very much for your efforts and responsiveness. I downloaded the `fra.traineddata` file, but I had to modify the path in my `config.json` file:

`"tesseractPath": "P:\\github\\LorcanaJSON" ==> "tesseractPath": "C:\\Program Files\\Tesseract-OCR\\tessdata"`

Thanks again! I look forward to seeing the improvements you make.

**Comment by Didero** [comment]
Glad to hear it works for you now!
